version: "3.8"

services:
  # Application TIWAP
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py  # ⚠️ Assure-toi que c'est bien ton fichier principal Flask
      - MONGO_URI=mongodb://username:password@db:27017/TIWAP
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - tiwap_network

  # Base de données MongoDB
  db:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=TIWAP
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - "27017:27017"
    networks:
      - tiwap_network

  zap:
    image: ghcr.io/zaproxy/zaproxy:latest
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - app
    networks:
      - tiwap_network

networks:
  tiwap_network:
    driver: bridge