name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.6
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose up -d --build

      - name: Wait for TIWAP to be ready...
        run: |
          echo "Waiting for TIWAP to be ready..."
          for i in {1..10}; do
            if curl --fail http://localhost:5001; then
              echo "TIWAP is up!"
              break
            fi
            echo "Retrying in 5s... ($i/10)"
            sleep 5
          done
        shell: bash

      - name: Run ZAP scan from container
        run: |
          docker exec tiwap-zap-1 zap.sh -cmd -quickurl http://app:5000 -quickout /zap/zap-report.html

      - name: Copy ZAP HTML report to host
        run: |
          docker cp tiwap-zap-1:/zap/zap-report.html ./zap-report.html

      - name: Upload ZAP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: ./zap-report.html